- name: Install GlusterFS server
  apt:
    pkg:
      - glusterfs-server
    update_cache: yes

- name: Enable glusterd service
  service:
    name: glusterd
    enabled: yes
  notify: restart glusterd service

- name: Flush ansible handlers
  meta: flush_handlers
