#####################################################################
# Packages
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes
    autoremove: yes
  when: apt_update_packages|bool
  tags:
    - apt

- name: Install basic packages
  apt:
    pkg: "{{ apt_base_packages }}"
    update_cache: yes
  tags:
    - apt

#####################################################################
# Unattended upgrades

- include_role:
    name: unattended_upgrades
    apply:
      tags:
        - unattended-upgrades
  when: apt_enable_unattended_upgrades|bool
  tags:
    - unattended-upgrades

#####################################################################
# Network interfaces

- include_tasks: network_interfaces.yml
  when: net_config_interfaces|bool

#####################################################################
# Postfix setup

- include_tasks:
    file: setup_postfix.yml
    apply:
      tags:
        - postfix
  when: postfix_setup|bool
  tags:
    - postfix

#####################################################################
# Users
- include_role:
    name: users
  tags:
    - users

#####################################################################
# Firewall
# https://wiki.nftables.org/wiki-nftables/index.php/Quick_reference-nftables_in_10_minutes

- include_tasks: nftables.yml
  when: nft_configure|bool
  tags:
    - firewall

#####################################################################
# Fail2Ban

- include_tasks: fail2ban.yml
  when: fail2ban_configure|bool
  tags:
    - fail2ban

#####################################################################
# Setup logrotate

- include_tasks:
    file: logrotate.yml
    apply:
      tags:
        - logrotate
  when: logrotate_configure|bool
  tags:
    - logrotate

#####################################################################
# Setup remote syslog

- include_tasks: rsyslog.yml
  when: rsyslog_configure|bool
  tags:
    - syslog

#####################################################################
# Setup docker

- name: Install docker and docker-compose
  include_role:
    name: docker
    apply:
      tags:
        - docker
  when: docker_configure|bool
  tags:
    - docker

#####################################################################
# Setup GlusterFS server node

- name: Install GlusterFS server node
  include_role:
    name: glusterfs-server
    apply:
      tags:
        - glusterfs-server
  when: gluster_server_configure|bool
  tags:
    - glusterfs-server

#####################################################################
# Setup GlusterFS client

- name: Install GlusterFS client
  include_role:
    name: glusterfs-client
    apply:
      tags:
        - glusterfs-client
  when: gluster_client_configure|bool
  tags:
    - glusterfs-client

#####################################################################
# Install Postgres

- name: Install Postgres
  include_role:
    name: postgres
    apply:
      tags:
        - postgres
  when: postgres_configure|bool
  tags:
    - postgres
    - postgres-prometheus-exporter

#####################################################################
# Install Prometheus node exporter

- name: Install and configure Prometheus node exporter
  include_role:
    name: prometheus.prometheus.node_exporter
    apply:
      tags:
        - node_exporter
  when: node_exporter_configure|bool
  tags:
    - node_exporter

#####################################################################
# Reboot

- include_tasks: reboot.yml
  when: reboot_all|bool or reboot_if_required|bool
  tags:
    - reboot
    - reboot-if-required
