- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  tags:
    - reboot-if-required
    - reboot

- name: Reboot machine, that require it
  reboot:
  when: reboot_if_required|bool and reboot_required_file.stat.exists
  tags:
    - reboot-if-required

- name: Reboot all machines
  reboot:
  when: reboot_all|bool and ((reboot_if_required|bool and not reboot_required_file.stat.exists) or not reboot_if_required|bool)
  tags:
    - reboot