- name: Set mail hostname
  debconf:
    name: postfix
    question: postfix/mailname
    value: "{{ inventory_hostname }}"
    vtype: string

- name: Set mailer type
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: "Satellite system"
    vtype: select

- name: Set relay host
  debconf:
    name: postfix
    question: postfix/relayhost
    value: "{{ postfix_relayhost }}"
    vtype: string

- name: Install postfix package
  apt:
    name:
      - 'postfix'
    state: present

- name: Set alias for root mail user
  lineinfile:
    path: "/etc/aliases"
    regexp: '^root: sys@pod.cvut.cz'
    line: "root: sys@pod.cvut.cz"

- name: Generate new aliases
  command: newaliases